apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - env:
        - name: APP_SECRET_KEY
          value: xi3aiGiewip1ze7MFei9haotvoo9Wo4k
        - name: SQLALCHEMY_DATABASE_URI
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: SQLALCHEMY_DATABASE_URI
        - name: SQLALCHEMY_TRACK_MODIFICATIONS
          value: "True"
        image: app
        name: app
        resources: {}
      restartPolicy: Always
status: {}
